PAGES = ["https://zylo.com/blog/guide-saas-renewal/",
         "https://zylo.com/blog/saas-management/",
         "https://zylo.com/blog/saas-discovery/",
         "https://zylo.com/blog/what-is-saas-governance/",
         "https://zylo.com/blog/application-portfolio-management/",
         "https://zylo.com/blog/saas-management-optimization/",
         "https://zylo.com/blog/how-to-eliminate-shadow-it/",
         "https://zylo.com/blog/single-sign-on-security/",
         "https://zylo.com/blog/how-to-tell-if-employees-are-using-saas-tools/",
         "https://zylo.com/blog/4-ways-to-take-action-on-saas-usage-data/",
         "https://zylo.com/blog/usage-connect/",
         "https://zylo.com/blog/software-marketplace/",  
        ]
